### PR TITLE
Iteration

### PR DESCRIPTION
**Pull request by imahnama**
In-depth examples on how to use nested conditionals

### CODE REVIEW

**Comment by imahnama** [comment]
[Iteration](https://trello.com/c/b9ATnlx4/2-iteration)

**Comment by bqevin** [comment]
@imahnama How I would wish these be 3 PRs 😑

**Comment by bqevin** [comment]
Keep first one `conditions` then open for `loops` and `iteration`

**Comment by imahnama** [comment]
> @imahnama How I would wish the on their way

**Comment by bqevin** [comment]
Could you only have one file i.e `iteration.py` for this PR. 

ION : Great choice of exercise.

**Pull request merged**
